name: 'The Lazy & Hungry'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2831541
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#160E15'
    - '#FFFFF4'
    - '#7F5C41'
    - '#DFCFB4'
    - '#01424A'
  brandStrength: 0.6556166
  lightness: 0.5368465
  saturation: 0.8731282
  rhythmicContrast: 0.3994734
purpose: []
